import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/utils/theme-provider";
import TanstackProvider from "@/components/provider/TanstackProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hill Now",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={"dark"}>
        <TanstackProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >

              {children}
          </body>
        </TanstackProvider>
      </html>
    </ClerkProvider>
  );
}
